### ISSUE TITLE
kudos

### ISSUE THREAD

**Issue by rismoney** [kireevco/wimaging#1]
first kudos to you for this project.

I plan on modifying this to do a few things
I only really focus on 2012 deployments, so I have been trying to get everything into an image offline, without using a hyperv to instantiate and recapture.
1. idempotent management around the wim. config file driven like you have.
2. ease of use. feature injection simplification, ie $tftp=present for all the features
3. include offlinewsus capability, with ease of use.  devise a method to eliminate any intervention

**Comment by DimmKirr** [comment]
first, sorry, missed a notification on that issue, 

All makes sense to me. Feel free to submit a pull request.

I still would like to keep initial imaging step for 2008R2, since it has issues with injecting .net and updates to it. But we can move it to "Legacy steps for 2008R2" and hide it from the main one.

I also wanted to add some instructions as well as Pxeboot / Unattend.xml plugins for foreman. thereis a repo (almost empty now) kireevco/foreman-wimaging

**Comment by DimmKirr** [comment]
Hi, I'm cleaning up,

Any good stuff added to the fork? Maybe merge something and close the issue?
