### ISSUE TITLE
Windows booting into Recovery screen

### ISSUE THREAD

**Issue by kgalal** [kireevco/wimaging#44]
I had the same issue mentioned earlier (issue #31 ), where i copied the "tell foreman" part to the instal script, which seems to have updated the tftp file to boot from disk on the foreman server, rather than keep getting stuck in the PXE/reimaging loop. However, when the VM boots again to book from from local disk, it ends up at the "Recovery Screen" for windows. I'm not sure if this is due to me not copying the "tell foreman" part correctly, or some other driver issue.

**Comment by helge000** [comment]
## If fist boot device is network, the host will become stuck in a boot/install loop

**Tell Foreman** effectively disables build mode in Foreman. On Linux, this works very well, denying clients to boot into the installer - thus booting from `disk0` usually. On windows, this does not work:

- The reason for this behaviour is in the way windows installs working, booting multiple times during installation
- We can disable build mode **only after** puppet is installed, since the autosign entry is removed when build mode is ended
- Ending build mode early might also lead to more silently failed builds as we cannot know whatever finish as running at all

However if you do not use puppet, you can try calling a finished build as the last thing in the script

### Recommendation
Our Windows VMs and bare metal hosts are set to boot from the first disk and second from network. If it is a new computer, the disk will be blank and network boot is used - until a valid boot sector is present on `disk0`. 
If the host is a VM, I have a hook in place witch kills the machine and replaces disk0 with a blank disk. Bare Metal hosts will require manual work however.

Did this clean up the confusion a litte?

**Comment by kgalal** [comment]
Thank you for the prompt response to my question above. I can see how booting multiple times during the build process is resulting in it being stuck in an endless loop.

I have followed your recommendation, and I was successfully able to provision a Window 8.1 VM. I agree, which is great. 

Please go ahead and close this issue, and many thanks for your help.
